name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v7
    - uses: actions/setup-python@v7
      with:
        python-version: "3.14"
    - run: pip install -r bin/requirements.txt
    - run: make --always-make
    - uses: actions/upload-artifact@v7
      with:
        name: chess-openings
        path: dist/
